model_list:
  # - model_name: gemini-2.5-flash        # 客户端（你的代码）调用时使用的名称
  #   litellm_params:
  #     # 格式为 provider/model-name
  #     model: vertex_ai/gemini-2.5-flash
    
  - model_name: gemini-3-pro-preview
    litellm_params:
      model: vertex_ai/gemini-3-pro-preview
  
  - model_name: gemini-3-pro
    litellm_params:
      model: vertex_ai/gemini-3-pro-preview

litellm_settings:
  # drop_params: True
  # set_verbose: False
  vertex_project: os.environ/PROJECT_ID
  vertex_location: os.environ/REGION

# general_settings: 
#   master_key: sk-123456